"""initial schema (F1-01): all MVP entities, each tenant-scoped from the start.

Autogenerated from the models and reviewed by hand. The bookings partial unique index
(``uq_bookings_active_slot``, ``WHERE status <> 'cancelled'``) is PostgreSQL-specific and is the
database-level belt against double-booking (RF-04).

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-09 17:02:26.776113
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_keys_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_api_keys_prefix'))
    )
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('schedules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_schedules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_schedules_tenant_id_name'))
    )
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id_email'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.LargeBinary(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhooks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhooks'))
    )
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('date_overrides',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ranges', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_date_overrides_schedule_id_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_date_overrides_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_date_overrides')),
    sa.UniqueConstraint('tenant_id', 'schedule_id', 'date', name=op.f('uq_date_overrides_tenant_id_schedule_id_date'))
    )
    op.create_index(op.f('ix_date_overrides_schedule_id'), 'date_overrides', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_date_overrides_tenant_id'), 'date_overrides', ['tenant_id'], unique=False)
    op.create_table('event_types',
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('buffer_before_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('buffer_after_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_notice_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_advance_seconds', sa.Integer(), nullable=False),
    sa.Column('increment_seconds', sa.Integer(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_event_types_host_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_event_types_schedule_id_schedules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_event_types_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_types')),
    sa.UniqueConstraint('tenant_id', 'slug', name=op.f('uq_event_types_tenant_id_slug'))
    )
    op.create_index(op.f('ix_event_types_host_id'), 'event_types', ['host_id'], unique=False)
    op.create_index(op.f('ix_event_types_schedule_id'), 'event_types', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_event_types_tenant_id'), 'event_types', ['tenant_id'], unique=False)
    op.create_table('external_connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_external_connections_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_connections')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'provider', 'account_email', name='uq_external_connections_identity')
    )
    op.create_index(op.f('ix_external_connections_tenant_id'), 'external_connections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_external_connections_user_id'), 'external_connections', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhook_deliveries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name=op.f('fk_webhook_deliveries_webhook_id_webhooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index('ix_webhook_deliveries_due', 'webhook_deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('bookings',
    sa.Column('event_type_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='booking_status', native_enum=False, length=16), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=320), nullable=False),
    sa.Column('guest_timezone', sa.String(length=64), nullable=False),
    sa.Column('guest_notes', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=1024), nullable=True),
    sa.Column('rescheduled_from_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], name=op.f('fk_bookings_event_type_id_event_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['bookings.id'], name=op.f('fk_bookings_rescheduled_from_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bookings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_event_type_id'), 'bookings', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_index('uq_bookings_active_slot', 'bookings', ['tenant_id', 'event_type_id', 'start_at'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    op.create_table('busy_cache',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], name=op.f('fk_busy_cache_connection_id_external_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_busy_cache_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_busy_cache'))
    )
    op.create_index(op.f('ix_busy_cache_tenant_id'), 'busy_cache', ['tenant_id'], unique=False)
    op.create_index('ix_busy_cache_window', 'busy_cache', ['tenant_id', 'connection_id', 'start_at'], unique=False)
    op.create_table('external_calendar_links',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('external_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], name=op.f('fk_external_calendar_links_connection_id_external_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_external_calendar_links_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_calendar_links')),
    sa.UniqueConstraint('tenant_id', 'connection_id', 'external_calendar_id', name='uq_external_calendar_links_calendar')
    )
    op.create_index(op.f('ix_external_calendar_links_connection_id'), 'external_calendar_links', ['connection_id'], unique=False)
    op.create_index(op.f('ix_external_calendar_links_tenant_id'), 'external_calendar_links', ['tenant_id'], unique=False)
    op.create_table('guest_tokens',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_guest_tokens_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_guest_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_guest_tokens_token_hash'))
    )
    op.create_index(op.f('ix_guest_tokens_booking_id'), 'guest_tokens', ['booking_id'], unique=False)
    op.create_index(op.f('ix_guest_tokens_tenant_id'), 'guest_tokens', ['tenant_id'], unique=False)
    op.create_table('sent_notifications',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_sent_notifications_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sent_notifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_notifications')),
    sa.UniqueConstraint('tenant_id', 'booking_id', 'kind', name=op.f('uq_sent_notifications_tenant_id_booking_id_kind'))
    )
    op.create_index(op.f('ix_sent_notifications_booking_id'), 'sent_notifications', ['booking_id'], unique=False)
    op.create_index(op.f('ix_sent_notifications_tenant_id'), 'sent_notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_notifications_tenant_id'), table_name='sent_notifications')
    op.drop_index(op.f('ix_sent_notifications_booking_id'), table_name='sent_notifications')
    op.drop_table('sent_notifications')
    op.drop_index(op.f('ix_guest_tokens_tenant_id'), table_name='guest_tokens')
    op.drop_index(op.f('ix_guest_tokens_booking_id'), table_name='guest_tokens')
    op.drop_table('guest_tokens')
    op.drop_index(op.f('ix_external_calendar_links_tenant_id'), table_name='external_calendar_links')
    op.drop_index(op.f('ix_external_calendar_links_connection_id'), table_name='external_calendar_links')
    op.drop_table('external_calendar_links')
    op.drop_index('ix_busy_cache_window', table_name='busy_cache')
    op.drop_index(op.f('ix_busy_cache_tenant_id'), table_name='busy_cache')
    op.drop_table('busy_cache')
    op.drop_index('uq_bookings_active_slot', table_name='bookings', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_type_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_due', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_external_connections_user_id'), table_name='external_connections')
    op.drop_index(op.f('ix_external_connections_tenant_id'), table_name='external_connections')
    op.drop_table('external_connections')
    op.drop_index(op.f('ix_event_types_tenant_id'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_schedule_id'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_host_id'), table_name='event_types')
    op.drop_table('event_types')
    op.drop_index(op.f('ix_date_overrides_tenant_id'), table_name='date_overrides')
    op.drop_index(op.f('ix_date_overrides_schedule_id'), table_name='date_overrides')
    op.drop_table('date_overrides')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    # ### end Alembic commands ###
