"""The workflow-template renderer (RF-24): the body is DATA, and it is never instructions.

A tenant authors a template; a workflow step renders it and sends it. Two separate guarantees hold
this together, and conflating them is how this goes wrong:

.. rubric:: 1. The allow-list governs WHICH variables exist

Substitution is a single strict pass over ``{{name}}``, where ``name`` must be a bare identifier
drawn from :data:`ALLOWED_VARIABLES`. Anything else inside ``{{ }}`` — an expression, an attribute
access, a call — is a loud :class:`TemplateError`, never an evaluation and never a silently-empty
hole. **There is no Jinja, no ``eval``, and no expression evaluator anywhere in this module**; a
template is text with holes in it, and the holes are filled from a fixed dictionary.

The substituted text is **never re-scanned**. ``re.sub`` with a function replacement writes the
value in and moves on, so a guest who books under the name ``{{host_name}}`` gets exactly the string
``{{host_name}}`` in the body — not the host's name. A renderer that loops "until no placeholders
remain" leaks the whole context to anyone who can type into the booking form.

.. rubric:: 2. The escaping governs WHAT THEY MAY CONTAIN

This is the half a strict allow-list lulls you into skipping, and it is the one with a victim.
``{{guest_name}}`` comes from the **public booking form**, and it is rendered into an email **to the
host**, into WhatsApp/SMS, and into the admin panel. Unescaped, a guest writes their name as
``Click https://evil.example/login to confirm`` and phishes the host inside a message this product
sent under its own branding. So every VALUE (never the template — the tenant owns its own layout) is
put through:

* **control + bidi + zero-width stripping** — a right-to-left override reverses how the rest of the
  line *displays*; zero-width characters hide text from the human but not from the client;
* **newline collapsing** — a value is ONE line. An injected newline forges a signature or a fake
  "system" block underneath the real body;
* **URL defanging** in the free-text guest fields — a link is rendered inert (``evil[.]example``)
  rather than deleted, so the host still sees exactly what was submitted;
* **markup neutralisation per channel** — WhatsApp renders ``*bold*`` / ``_italic_`` /
  ``~strike~`` / mono, which a guest can use to forge an official-looking notice;
* **a length cap per variable** — not merely per message: an unbounded name pushes the real content
  out of an SMS segment budget, and runs up the bill;
* **channel escaping** — HTML for email (the body is HTML-capable), plain text for WhatsApp/SMS.

The product's own links (``cancel_url`` / ``reschedule_url`` / ``meeting_url``) are generated by
this system, not typed by a guest, so they are NOT defanged — the message exists to deliver them.
"""

from __future__ import annotations

import html
import re
import unicodedata
from collections.abc import Mapping
from dataclasses import dataclass, fields
from typing import assert_never

from aethercal.server.channels import Channel

ALLOWED_VARIABLES = frozenset(
    {
        "guest_name",
        "guest_email",
        "event_title",
        "start_local",
        "end_local",
        "timezone",
        "host_name",
        "cancel_url",
        "reschedule_url",
        "meeting_url",
    }
)
"""The complete vocabulary a tenant template may reference. Anything else is an error."""

MAX_VARIABLE_LENGTH = 200
"""The cap on one substituted value (the product's own URLs get :data:`MAX_URL_LENGTH`)."""

MAX_URL_LENGTH = 512
"""A generous cap for the system-generated links, which must survive intact to be usable."""

MAX_BODY_LENGTH: Mapping[Channel, int] = {
    # Twilio concatenates up to 1600 characters; past that the send is rejected outright.
    Channel.SMS: 1600,
    # WhatsApp's text body limit.
    Channel.WHATSAPP: 4096,
    # Email has no practical limit worth enforcing here.
    Channel.EMAIL: 100_000,
}
"""The cap on the fully-rendered body, per channel — a spend guard as much as a protocol limit."""

_TRUNCATION_MARK = "…"

# The guest-supplied FREE-TEXT fields: unstructured, typed by whoever filled in the public form.
# These get URL defanging and markup neutralisation on top of everything every value gets.
_FREE_TEXT = frozenset({"guest_name"})

# Guest-supplied but STRUCTURED: the schema validates it as an email address. It must stay readable
# (defanging it would render "ada@example[.]com" to every host, for every booking), so it is only
# defanged when it does NOT have the shape of an address — i.e. when the upstream validator was
# bypassed by some other creation path. Defence in depth without breaking the 99.99% case.
_STRUCTURED_GUEST = frozenset({"guest_email"})

# System-generated links. NOT defanged: delivering them is the entire point of the message.
_PRODUCT_URLS = frozenset({"cancel_url", "reschedule_url", "meeting_url"})

# A placeholder is ANY `{{ ... }}` span. Deliberately greedy about what it CATCHES and strict about
# what it ACCEPTS: catching `{{config.items()}}` and then rejecting it is what makes an expression a
# loud error instead of inert text that quietly renders nothing.
_PLACEHOLDER = re.compile(r"\{\{(.*?)\}\}", re.DOTALL)

# What is allowed INSIDE a placeholder: a bare identifier, optionally padded. Nothing else.
_BARE_IDENTIFIER = re.compile(r"\A\s*([A-Za-z_][A-Za-z0-9_]*)\s*\Z")

# A conservative email shape, used only to decide whether `guest_email` still looks like an address.
_EMAIL_SHAPE = re.compile(r"\A[^@\s]+@[^@\s]+\.[A-Za-z]{2,}\Z")

# URL-ish tokens in free text. Three branches, widest first: an explicit (or scheme-relative)
# `//host/...`, a `www.` host, and a bare `label.label[/path]` domain. The bare branch is
# deliberately over-broad — it also catches "Ph.D." — because the failure it prevents (a live
# phishing link in a message to the host) is far worse than a defanged abbreviation in a name.
_URLISH = re.compile(
    r"""(?xi)
    (?:[a-z][a-z0-9+.\-]*:)?//[^\s]+
    | www\.[^\s]+
    | [a-z0-9](?:[a-z0-9\-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?)+(?:/[^\s]*)?
    """
)

# WhatsApp's inline formatting markers. Stripped from VALUES only — a tenant's own template may use
# them freely, because the tenant is the author of their own message.
_WHATSAPP_MARKUP = re.compile(r"[*_~`]")

# Zero-width and bidirectional-control code points: invisible to the reader, meaningful to the
# renderer. `Cf` (format) covers the RLO/LRO/PDF/isolates and the zero-width joiners.
_INVISIBLE_CATEGORY = "Cf"
_CONTROL_CATEGORY = "Cc"


class TemplateError(Exception):
    """A template that can never render: bad syntax, or a variable outside the allow-list.

    Terminal by nature — retrying a malformed template can only fail again — so the workflow step
    that carries it is SKIPPED with its reason rather than retried into the dead-letter."""


class UnknownVariableError(TemplateError):
    """The template references a variable that is not in :data:`ALLOWED_VARIABLES`."""


@dataclass(frozen=True, slots=True)
class TemplateContext:
    """The values for one render. **Every allow-listed variable is present**, always.

    Completeness is the contract, and it is what stops a typo in the context builder from silently
    blanking a variable in every message a tenant ever sends. A value may legitimately be EMPTY (an
    in-person booking has no meeting URL); it may never be MISSING.
    """

    guest_name: str
    guest_email: str
    event_title: str
    start_local: str
    end_local: str
    timezone: str
    host_name: str
    cancel_url: str
    reschedule_url: str
    meeting_url: str

    def as_mapping(self) -> Mapping[str, str]:
        """The context as a plain ``{name: value}`` mapping."""
        return {field.name: getattr(self, field.name) for field in fields(self)}


@dataclass(frozen=True, slots=True)
class RenderedMessage:
    """A rendered template: the body, and the subject for the channels that have one."""

    subject: str | None
    body: str


def validate_template_body(body: str, subject: str | None = None) -> None:
    """Raise if ``body``/``subject`` reference anything outside the allow-list. Returns ``None``.

    The admin's template CRUD calls this when a template is SAVED, so a tenant learns about a typo
    at authoring time instead of via a message that never arrives. It reports EVERY offending name
    at once rather than one per round-trip."""
    unknown: list[str] = []
    malformed: list[str] = []
    for source in (body, subject or ""):
        for match in _PLACEHOLDER.finditer(source):
            inner = match.group(1)
            identifier = _BARE_IDENTIFIER.match(inner)
            if identifier is None:
                malformed.append(inner.strip())
            elif identifier.group(1) not in ALLOWED_VARIABLES:
                unknown.append(identifier.group(1))

    if malformed:
        raise TemplateError(
            f"a template placeholder must be a bare variable name, got {malformed!r}. "
            "The body is DATA: there is no expression evaluation, no attribute access and no call."
        )
    if unknown:
        allowed = ", ".join(sorted(ALLOWED_VARIABLES))
        raise UnknownVariableError(
            f"unknown template variable(s) {unknown!r}; the allow-list is: {allowed}"
        )


def render_template(
    body: str, *, subject: str | None, context: TemplateContext, channel: Channel
) -> RenderedMessage:
    """Render ``body`` (and ``subject``) for ``channel``, substituting only allow-listed variables.

    Raises :class:`TemplateError` for a template that can never render. Every substituted VALUE is
    sanitised for the channel first (see the module docstring) — the template itself is the tenant's
    own layout and is left alone."""
    values = context.as_mapping()
    rendered_body = _substitute(body, values=values, channel=channel)
    rendered_subject = (
        None if subject is None else _substitute(subject, values=values, channel=channel)
    )
    if rendered_subject is not None:
        # A subject is ONE line, whoever wrote it. A newline here is header injection — and unlike a
        # value (already collapsed below), this one could come from the tenant's own template.
        rendered_subject = _collapse_whitespace(rendered_subject)

    return RenderedMessage(
        subject=rendered_subject, body=_cap(rendered_body, MAX_BODY_LENGTH[channel])
    )


def _substitute(source: str, *, values: Mapping[str, str], channel: Channel) -> str:
    """One strict pass.

    ``re.sub`` never re-scans what it wrote. That is load-bearing, not incidental — see the module
    docstring: it is what stops a guest-supplied ``{{host_name}}`` from expanding."""

    def _replace(match: re.Match[str]) -> str:
        inner = match.group(1)
        identifier = _BARE_IDENTIFIER.match(inner)
        if identifier is None:
            raise TemplateError(
                f"a template placeholder must be a bare variable name, got {inner.strip()!r}. "
                "The body is DATA: no expression evaluation, no attribute access, no call."
            )
        name = identifier.group(1)
        if name not in ALLOWED_VARIABLES:
            allowed = ", ".join(sorted(ALLOWED_VARIABLES))
            raise UnknownVariableError(
                f"unknown template variable {name!r}; the allow-list is: {allowed}"
            )
        return _sanitise(values[name], name=name, channel=channel)

    return _PLACEHOLDER.sub(_replace, source)


def _sanitise(value: str, *, name: str, channel: Channel) -> str:
    """Make one guest/tenant value safe to place inside ``channel``'s message body.

    The order matters: strip the invisible characters BEFORE looking for links (otherwise a
    zero-width space inside ``evil.example`` hides the domain from the defanger), and escape LAST
    (so the escaping applies to the final text and cannot itself be smuggled through)."""
    cleaned = _collapse_whitespace(_strip_invisible(value))

    if name in _FREE_TEXT or (name in _STRUCTURED_GUEST and not _EMAIL_SHAPE.match(cleaned)):
        # Free text from the booking form — or a "guest_email" that no longer looks like an address,
        # which means some creation path bypassed the schema validator. Treat it as hostile.
        cleaned = _defang_urls(cleaned)
        cleaned = _neutralise_markup(cleaned, channel)

    limit = MAX_URL_LENGTH if name in _PRODUCT_URLS else MAX_VARIABLE_LENGTH
    return _escape_for(_cap(cleaned, limit), channel)


def _strip_invisible(value: str) -> str:
    """Drop control characters and the invisible formatting code points (bidi overrides, ZWJ...).

    Tabs/newlines/carriage returns are left for :func:`_collapse_whitespace` to fold into a space,
    so a name written across two lines still reads as two words rather than being run together."""
    kept: list[str] = []
    for char in value:
        category = unicodedata.category(char)
        if category == _INVISIBLE_CATEGORY:
            continue
        if category == _CONTROL_CATEGORY and char not in "\t\n\r":
            continue
        kept.append(char)
    return "".join(kept)


def _collapse_whitespace(value: str) -> str:
    """Collapse every run of whitespace (newlines included) into one space. A value is ONE line."""
    return re.sub(r"\s+", " ", value).strip()


def _defang_urls(value: str) -> str:
    """Render any link inert, without deleting it — the host must still see what was submitted."""

    def _defang(match: re.Match[str]) -> str:
        return match.group(0).replace(".", "[.]").replace(":", "[:]")

    return _URLISH.sub(_defang, value)


def _neutralise_markup(value: str, channel: Channel) -> str:
    """Strip the markup THIS channel would render, so a guest cannot forge an official notice."""
    match channel:
        case Channel.WHATSAPP:
            return _WHATSAPP_MARKUP.sub("", value)
        case Channel.SMS:
            # SMS is plain text end to end: there is no markup to neutralise.
            return value
        case Channel.EMAIL:
            # HTML escaping (applied last, in _escape_for) IS the neutralisation for email.
            return value
        case _ as unreachable:  # pragma: no cover - exhaustive over Channel
            assert_never(unreachable)


def _escape_for(value: str, channel: Channel) -> str:
    """Escape a value for the channel that will render it."""
    match channel:
        case Channel.EMAIL:
            # The email body is HTML-capable, so a value must never be able to introduce markup.
            return html.escape(value, quote=True)
        case Channel.WHATSAPP | Channel.SMS:
            return value
        case _ as unreachable:  # pragma: no cover - exhaustive over Channel
            assert_never(unreachable)


def _cap(value: str, limit: int) -> str:
    """Truncate to ``limit`` characters, marking the cut so a reader knows the text was clipped."""
    if len(value) <= limit:
        return value
    return value[: limit - len(_TRUNCATION_MARK)] + _TRUNCATION_MARK


__all__ = [
    "ALLOWED_VARIABLES",
    "MAX_BODY_LENGTH",
    "MAX_URL_LENGTH",
    "MAX_VARIABLE_LENGTH",
    "RenderedMessage",
    "TemplateContext",
    "TemplateError",
    "UnknownVariableError",
    "render_template",
    "validate_template_body",
]
